services:
  server:
    container_name: "server"
    build:
      context: .
    # depends_on:
    #   postgres:
    #     condition: service_started
    #   langtrace:
    #     condition: service_healthy
    volumes:
      - "./:/app"
    environment:
      - OPENAI_API_KEY=sk-<>
    ports:
      - "8000:8000"
    command:
      ["sh", "-c", "daphne -b 0.0.0.0 -p 8000 langtrace_issue.asgi:application"]

  # langtrace:
  #   container_name: langtrace
  #   image: scale3labs/langtrace-client:latest
  #   working_dir: /app
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"

  #   healthcheck:
  #     test: "wget --no-verbose --tries=1 --spider -q http://langtrace:3000 || exit 1"
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  #   depends_on:
  #     # postgres:
  #     #   condition: service_started
  #     clickhouse:
  #       condition: service_healthy

  # clickhouse:
  #   container_name: clickhouse
  #   image: clickhouse/clickhouse-server:24.5.1.1763-alpine
  #   environment:
  #     - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
  #     - CLICKHOUSE_PASSWORD=${CLICK_HOUSE_PASSWORD}
  #     - CLICKHOUSE_USER=${CLICK_HOUSE_USER}
  #     - CLICKHOUSE_DB=${CLICK_HOUSE_DATABASE_NAME}
  #   ports:
  #     - "8123:8123"
  #     - "9000:9000"
  #   healthcheck:
  #     test:
  #       [
  #         "CMD-SHELL",
  #         "wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1",
  #       ]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 15s
  #     start_interval: 5s
  #   volumes:
  #     - clickhouse:/var/lib/clickhouse

  # postgres:
  #   container_name: "postgres"
  #   restart: always
  #   # image: pgvector/pgvector:pg16
  #   image: postgres:latest
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: chatbot
  #   volumes:
  #     - pgdatabase:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  pgdatabase:
  clickhouse:
